### ISSUE TITLE
Arrange team members who participate the first meeting with the instructor and their tasks. 

### ISSUE THREAD

**Issue by JoyKuan** [DS-560/ENSO_forecast#1]
Although we have integrated our project scope during the group meeting, there are still some uncertain parts such as Objectives and Metrics that need to be discussed and clarified with the professor to make sure we are on the right track with the project. Thus, the project manager needs someone to take notes and someone listen and think of questions during the meeting with the professor.

**Comment by JoyKuan** [comment]
I can be a note-taking person during the meeting.

**Comment by jieqiong-pang** [comment]
I am willing to communicate with the professor to confirm the scope of our project, make sure we are on the right track.

**Comment by xielidawan** [comment]
We will have the meeting today at 8:30 pm
